message: 'Hello from dev env'

spring:
  application:
    name: loan-service
  jpa:
    show-sql: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
logging:
  level:
    root: ERROR
    com.cts.loan: DEBUG
