spring:
  application:
    name: user-service
    
  jpa:
    show-sql: false  

redis:
  configuration:
    secure: true
    
 test: development
 
 logging:
  level:
    com:
      cts:
        user: DEBUG

